# Generated by Django 3.2.16 on 2023-02-08 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Please enter plant's name...", max_length=250, verbose_name="Plant's name")),
                ('first_date', models.DateTimeField(default=datetime.datetime(2023, 2, 8, 21, 18, 21, 891430), verbose_name='First water date')),
                ('water_after', models.IntegerField(default=None, null=True, verbose_name='Days to next watering')),
                ('water_ml', models.IntegerField(default=None, null=True, verbose_name='Water amount in ml')),
                ('check_out', models.DateTimeField(blank=True, default=None, null=True)),
                ('photo', models.ImageField(default=None, null=True, upload_to='gallery', verbose_name='Photo')),
            ],
        ),
    ]
